/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbars: typeof import('./renderer/src/components/Appbars.vue')['default']
    JsEditor: typeof import('./renderer/src/components/JsEditor.vue')['default']
    Main: typeof import('./renderer/src/components/Main.vue')['default']
    PageHeader: typeof import('./renderer/src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebars: typeof import('./renderer/src/components/Sidebars.vue')['default']
    Title: typeof import('./renderer/src/components/Title.vue')['default']
    Versions: typeof import('./renderer/src/components/Versions.vue')['default']
  }
}
